AirGenerator "enable" method for OC & CC
LemADEC/WarpDrive pull request #226
Opened 2016-12-07 17:10 UTC by TxN

Added computer control to air generator tile entity.
get/set property enabled()

This is my very first attempt to mod Minecraft, but it seems to be working.

2016-12-07 22:56 UTC, LemADEC requested changes
Seems functional.
Please amend with the requested changes.

2016-12-07 22:56 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
> +	private boolean generatorEnabled = true;
This is a air generator, no need to remind it in the property name here. Change it to "isEnabled" to be consistent with the rest of the mod.

2016-12-07 22:56 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
> +			if (energy_consume(WarpDriveConfig.AIRGEN_ENERGY_PER_NEWAIRBLOCK, true) && generatorEnabled) {
You want to check the enabled state first as it's less CPU intensive than check energy consumption.

2016-12-07 22:56 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
> +	public Object[] enabled(Object[] arguments) {
Method should be named "enable" to be consistent with the rest of the API.

2016-12-07 22:56 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
> +		} catch (Exception exception) {
Superfluous try/catch here. The toBool can't fails since arguments length is already tested ahead.

2016-12-07 22:56 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
> +				generatorEnabled = newEnable;
You can directly assign the value, no need for extra variable here.

2016-12-07 22:56 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
> +		return new Object[] { generatorEnabled};
Missing space before final }

2016-12-07 22:56 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
>  		cooldownTicks++;
Extraneous tabulation

2016-12-08 04:13 UTC, TxN commented
Done. Did I miss something?

2016-12-08 20:33 UTC, LemADEC requested changes

2016-12-08 20:33 UTC, LemADEC commented on src/main/java/cr0s/warpdrive/block/TileEntityAirGenerator.java
> +		isEnabled = tag.getBoolean("generatorEnabled");
Change tag name to enabled to be consistent with other blocks

2016-12-09 02:39 UTC, TxN commented
Done.

2016-12-09 21:59 UTC, merged